### ISSUE TITLE
This package does not working on atom 0.139.0

### ISSUE THREAD

**Issue by honmaaax** [screeny05/language-html-swig#1]
Hello. Could you check on this version?

**Comment by screeny05** [comment]
I'll check this, but it could take about a week. If you need this and it
doesn't work i'll suggest upgrading to another version.
Am 26.10.2014 13:20 schrieb "Hitoshi Honma" notifications@github.com:

**Comment by screeny05** [comment]
wontfix

**Comment by honmaaax** [comment]
Thank you!
