### ISSUE TITLE
This Extension Does not Inherently Work for Files With the .html File Extension

### ISSUE THREAD

**Issue by bookercodes** [screeny05/language-html-swig#9]
Hello, @screeny05 

Well done on building this _awesome_ extension, I just have one small problem that I would _love_ your input on.

I use the **.html** extension for my Swig templates:

![](http://i.imgur.com/gl7YUZs.png)

However, this extension only picks up Swig grammar and snippets for files with the **.swig** extension :disappointed:.

I _cannot_ use the **.swig** extension because that would break [Emmet](http://emmet.io/) (also, I prefer **.html** but that is not a good reason :stuck_out_tongue:).

My instinct is to fork this repository and to change the detected extension from **.swig** to **.html** (e.g. [here](https://github.com/screeny05/language-html-swig/blob/master/grammars/html%20%28swig%29.cson#L2)). I would maintain the fork on my profile which I _think_ is in accordance with your licence.

I am curious as to whether you have encountered this issue before and if so, do you have a solution? 

Many Thanks,
@alexbooker

**Comment by screeny05** [comment]
Hey @alexbooker,

You might want to have a look at [this issue](https://discuss.atom.io/t/force-grammar-usage-for-file-extension/15154/6) which gives advice on how to set a specific grammar for a file-extension locally in your editor.

Otherwise you are able to change the current Grammar via the Shortcut: `CTRL`+`SHIFT`+`L`

I hope this helps.

**Comment by bookercodes** [comment]
Thank you :heartbeat: 

I came across [this issue](https://github.com/atom/atom/issues/1718) but it was not helpful. I about to read [this answer](https://stackoverflow.com/questions/24653727/github-atom-how-to-apply-a-particular-syntax-highlighting-to-some-files-based-o) now.

**Comment by screeny05** [comment]
Is this resolved?

**Comment by bookercodes** [comment]
I never did figure it out. It was taking too much time so I had to pack it in.

**Comment by animabear** [comment]
You can make it by the following steps now:

setting－packages－language-html-swig－View code, then modify the  **grammars/html (swig).cson**

``` javascript
fileTypes: [
  "tpl" // the extension you want
]
```
